### ISSUE TITLE
設定を保存する

### ISSUE THREAD

**Issue by ykws** [ykws/OneTimePasswordExample#15]
![next-badge](https://img.shields.io/badge/review-next-blueviolet)

- 設定画面に戻ると毎回設定がリセットされてしまい使いづらいので、TOP画面と設定画面では同じ値を参照するようにして欲しいです。
設定値はローカルに保存してしまっても良いと思います。

_Originally posted by @ykws in https://github.com/ykws/OneTimePasswordExample/pull/10#pullrequestreview-793514188_

**Comment by NMai-source** [comment]
@ykws 
このローカルはiPhoneのローカルにデータを保存するということでしょうか？

**Comment by ykws** [comment]
@NMai-source はい。そうです。画面間で同じ値を共有できれば無理に保存する必要はないです。

**Comment by ykws** [comment]
#20 でローカルには保存しないですが、画面間で共有できる形になるので、合わせて対応
